FROM node:22-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

FROM base AS deps
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/client/package.json apps/client/
COPY apps/client-server/package.json apps/client-server/
COPY apps/admin/package.json apps/admin/
COPY packages/api/package.json packages/api/
COPY packages/i18n/package.json packages/i18n/
COPY packages/query/package.json packages/query/
COPY packages/schema/package.json packages/schema/
COPY packages/store/package.json packages/store/
COPY packages/types/package.json packages/types/
COPY packages/ui/package.json packages/ui/
COPY tooling/eslint/package.json tooling/eslint/
COPY tooling/typescript/package.json tooling/typescript/

# node_modules는 cache mount 대상이면 이미지 레이어에 남지 않아 COPY --from=deps 가 실패합니다.
RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm install --frozen-lockfile

FROM base AS builder
WORKDIR /app

ARG env=production
ENV NODE_ENV=${env}

ARG EXPO_PUBLIC_HOST_PATH=/
ENV EXPO_PUBLIC_HOST_PATH=${EXPO_PUBLIC_HOST_PATH}

ARG EXPO_PUBLIC_FIREBASE_WEB_API_KEY=
ENV EXPO_PUBLIC_FIREBASE_WEB_API_KEY=${EXPO_PUBLIC_FIREBASE_WEB_API_KEY}
ARG EXPO_PUBLIC_FIREBASE_WEB_APP_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_APP_ID=${EXPO_PUBLIC_FIREBASE_WEB_APP_ID}
ARG EXPO_PUBLIC_FIREBASE_WEB_AUTH_DOMAIN=
ENV EXPO_PUBLIC_FIREBASE_WEB_AUTH_DOMAIN=${EXPO_PUBLIC_FIREBASE_WEB_AUTH_DOMAIN}
ARG EXPO_PUBLIC_FIREBASE_WEB_MEASUREMENT_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_MEASUREMENT_ID=${EXPO_PUBLIC_FIREBASE_WEB_MEASUREMENT_ID}
ARG EXPO_PUBLIC_FIREBASE_WEB_MESSAGING_SENDER_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_MESSAGING_SENDER_ID=${EXPO_PUBLIC_FIREBASE_WEB_MESSAGING_SENDER_ID}
ARG EXPO_PUBLIC_FIREBASE_WEB_PROJECT_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_PROJECT_ID=${EXPO_PUBLIC_FIREBASE_WEB_PROJECT_ID}
ARG EXPO_PUBLIC_FIREBASE_WEB_STORAGE_BUCKET=
ENV EXPO_PUBLIC_FIREBASE_WEB_STORAGE_BUCKET=${EXPO_PUBLIC_FIREBASE_WEB_STORAGE_BUCKET}
ARG EXPO_PUBLIC_KAKAO_APP_KEY=
ENV EXPO_PUBLIC_KAKAO_APP_KEY=${EXPO_PUBLIC_KAKAO_APP_KEY}
ARG EXPO_PUBLIC_KAKAO_JS_KEY=
ENV EXPO_PUBLIC_KAKAO_JS_KEY=${EXPO_PUBLIC_KAKAO_JS_KEY}
ARG EXPO_PUBLIC_SENTRY_DNS=
ENV EXPO_PUBLIC_SENTRY_DNS=${EXPO_PUBLIC_SENTRY_DNS}
ARG EXPO_PUBLIC_BACKEND_API_URL=
ENV EXPO_PUBLIC_BACKEND_API_URL=${EXPO_PUBLIC_BACKEND_API_URL}
ARG EXPO_PUBLIC_UPLOAD_API_URL=
ENV EXPO_PUBLIC_UPLOAD_API_URL=${EXPO_PUBLIC_UPLOAD_API_URL}
ARG EXPO_PUBLIC_CHAT_API_URL=
ENV EXPO_PUBLIC_CHAT_API_URL=${EXPO_PUBLIC_CHAT_API_URL}
ARG EXPO_PUBLIC_IMAGE_API_URL=
ENV EXPO_PUBLIC_IMAGE_API_URL=${EXPO_PUBLIC_IMAGE_API_URL}

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package.json /app/pnpm-lock.yaml /app/pnpm-workspace.yaml ./
COPY --from=deps /app/apps ./apps
COPY --from=deps /app/packages ./packages
COPY --from=deps /app/tooling ./tooling

ARG EXPO_PUBLIC_SENTRY_DNS=
ENV EXPO_PUBLIC_SENTRY_DNS=${EXPO_PUBLIC_SENTRY_DNS}

ARG EXPO_PUBLIC_FIREBASE_WEB_API_KEY=
ENV EXPO_PUBLIC_FIREBASE_WEB_API_KEY=${EXPO_PUBLIC_FIREBASE_WEB_API_KEY}
ARG EXPO_PUBLIC_FIREBASE_WEB_AUTH_DOMAIN=
ENV EXPO_PUBLIC_FIREBASE_WEB_AUTH_DOMAIN=${EXPO_PUBLIC_FIREBASE_WEB_AUTH_DOMAIN}
ARG EXPO_PUBLIC_FIREBASE_WEB_PROJECT_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_PROJECT_ID=${EXPO_PUBLIC_FIREBASE_WEB_PROJECT_ID}
ARG EXPO_PUBLIC_FIREBASE_WEB_STORAGE_BUCKET=
ENV EXPO_PUBLIC_FIREBASE_WEB_STORAGE_BUCKET=${EXPO_PUBLIC_FIREBASE_WEB_STORAGE_BUCKET}
ARG EXPO_PUBLIC_FIREBASE_WEB_MESSAGING_SENDER_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_MESSAGING_SENDER_ID=${EXPO_PUBLIC_FIREBASE_WEB_MESSAGING_SENDER_ID}
ARG EXPO_PUBLIC_FIREBASE_WEB_APP_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_APP_ID=${EXPO_PUBLIC_FIREBASE_WEB_APP_ID}
ARG EXPO_PUBLIC_FIREBASE_WEB_MEASUREMENT_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_MEASUREMENT_ID=${EXPO_PUBLIC_FIREBASE_WEB_MEASUREMENT_ID}

COPY . .

ENV CI=true
RUN pnpm --filter @kakamu/i18n build
RUN pnpm --filter @kakamu/client build-web-${env}

FROM base AS runner
ARG env=production
ENV NODE_ENV=${env}

ARG EXPO_PUBLIC_HOST_PATH=/
ENV EXPO_PUBLIC_HOST_PATH=${EXPO_PUBLIC_HOST_PATH}

WORKDIR /app/apps/client-server

ENV PORT=3000

COPY apps/client-server/package.json ./
RUN --mount=type=cache,id=client-server-npm,target=/root/.npm \
    npm install --omit=dev

COPY --from=builder /app/apps/client-server/server ./server
RUN mkdir -p dist
COPY --from=builder /app/apps/client/dist ./dist

EXPOSE 3000
CMD ["node", "server/index.js"]
