FROM node:22-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

FROM base AS builder
WORKDIR /app

# 빌드: docker build --build-arg env=<이름> (기본값 production → NODE_ENV·.env.production)
ARG env=production
ENV NODE_ENV=${env}

# .env가 컨텍스트에 없을 때도 동일 경로로 빌드되도록 EXPO_PUBLIC_* 를 명시 전달합니다.
ARG EXPO_PUBLIC_HOST_PATH=/
ENV EXPO_PUBLIC_HOST_PATH=${EXPO_PUBLIC_HOST_PATH}

ARG EXPO_PUBLIC_KAKAO_APP_KEY=
ENV EXPO_PUBLIC_KAKAO_APP_KEY=${EXPO_PUBLIC_KAKAO_APP_KEY}
ARG EXPO_PUBLIC_KAKAO_JS_KEY=
ENV EXPO_PUBLIC_KAKAO_JS_KEY=${EXPO_PUBLIC_KAKAO_JS_KEY}

ARG EXPO_PUBLIC_SENTRY_DNS=
ENV EXPO_PUBLIC_SENTRY_DNS=${EXPO_PUBLIC_SENTRY_DNS}

ARG EXPO_PUBLIC_FIREBASE_WEB_API_KEY=
ENV EXPO_PUBLIC_FIREBASE_WEB_API_KEY=${EXPO_PUBLIC_FIREBASE_WEB_API_KEY}
ARG EXPO_PUBLIC_FIREBASE_WEB_AUTH_DOMAIN=
ENV EXPO_PUBLIC_FIREBASE_WEB_AUTH_DOMAIN=${EXPO_PUBLIC_FIREBASE_WEB_AUTH_DOMAIN}
ARG EXPO_PUBLIC_FIREBASE_WEB_PROJECT_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_PROJECT_ID=${EXPO_PUBLIC_FIREBASE_WEB_PROJECT_ID}
ARG EXPO_PUBLIC_FIREBASE_WEB_STORAGE_BUCKET=
ENV EXPO_PUBLIC_FIREBASE_WEB_STORAGE_BUCKET=${EXPO_PUBLIC_FIREBASE_WEB_STORAGE_BUCKET}
ARG EXPO_PUBLIC_FIREBASE_WEB_MESSAGING_SENDER_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_MESSAGING_SENDER_ID=${EXPO_PUBLIC_FIREBASE_WEB_MESSAGING_SENDER_ID}
ARG EXPO_PUBLIC_FIREBASE_WEB_APP_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_APP_ID=${EXPO_PUBLIC_FIREBASE_WEB_APP_ID}
ARG EXPO_PUBLIC_FIREBASE_WEB_MEASUREMENT_ID=
ENV EXPO_PUBLIC_FIREBASE_WEB_MEASUREMENT_ID=${EXPO_PUBLIC_FIREBASE_WEB_MEASUREMENT_ID}

COPY . .

ENV CI=true
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @kakamu/i18n build
RUN pnpm --filter @kakamu/client build-web-${env}

FROM base AS runner
ARG env=production
ENV NODE_ENV=${env}

ARG EXPO_PUBLIC_HOST_PATH=/
ENV EXPO_PUBLIC_HOST_PATH=${EXPO_PUBLIC_HOST_PATH}

WORKDIR /app/apps/client-server

ENV PORT=3000

COPY --from=builder /app/apps/client-server .
RUN npm install
RUN mkdir -p dist
COPY --from=builder /app/apps/client/dist ./dist

EXPOSE 3000
CMD ["node", "server/index.js"]
