export const PERSONA_NAME_MIN_LENGTH = 1;
export const PERSONA_NAME_MAX_LENGTH = 30;
export const PERSONA_DESCRIPTION_MIN_LENGTH = 1;
export const PERSONA_DESCRIPTION_MAX_LENGTH = 200;
export const PERSONA_GENRE_MAX_COUNT = 3;
