/** 백엔드 API 에러 응답 본문 (`{ code, message }`) */
export interface ApiErrorDetail {
  code: string;
  message: string;
}
export interface ApiErrorBody {
  detail: ApiErrorDetail;
}

export const API_ERROR_CODES = {
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  HASHTAG_LIMIT_EXCEEDED: 'HASHTAG_LIMIT_EXCEEDED',
  INVALID_REFERENCE_DATA: 'INVALID_REFERENCE_DATA',
  POST_CREATION_FAILED: 'POST_CREATION_FAILED',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  FORBIDDEN_POST_UPDATE: 'FORBIDDEN_POST_UPDATE',
  UNSUPPORTED_TARGET_TYPE: 'UNSUPPORTED_TARGET_TYPE',
  TARGET_NOT_FOUND: 'TARGET_NOT_FOUND',
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  FORBIDDEN_COMMENT_DELETE: 'FORBIDDEN_COMMENT_DELETE',
  FORBIDDEN_COMMENT_UPDATE: 'FORBIDDEN_COMMENT_UPDATE',
  FORBIDDEN_BLOCKED_COMMENT: 'FORBIDDEN_BLOCKED_COMMENT',
  ALREADY_EVALUATED: 'ALREADY_EVALUATED',
  MOVIE_NOT_FOUND: 'MOVIE_NOT_FOUND',
  PERSONA_NOT_FOUND_OR_FORBIDDEN: 'PERSONA_NOT_FOUND_OR_FORBIDDEN',
  PERSONA_LIMIT_EXCEEDED: 'PERSONA_LIMIT_EXCEEDED',
  MISSING_NICKNAME: 'MISSING_NICKNAME',
  DATABASE_SAVE_FAILED: 'DATABASE_SAVE_FAILED',
  SAME_NICKNAME: 'SAME_NICKNAME',
  FORBIDDEN_PERSONA_UPDATE: 'FORBIDDEN_PERSONA_UPDATE',
  PERSONA_NOT_FOUND: 'PERSONA_NOT_FOUND',
  MINIMUM_PERSONA_REQUIRED: 'MINIMUM_PERSONA_REQUIRED',
  PERSONA_DELETE_FAILED: 'PERSONA_DELETE_FAILED',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
